openapi: 3.0.3
info:
  title: API
  version: "1.0"
  description: |-
    - The api is secured by an api key.
    - The api is for the land department to manage the assets and their transactions.
    - The api is also used by 3rd party to submit transactions and incumbrances.
    - The api is also used by the operations team to check the health of the service.

servers:
  - url: http://localhost:3000/api/
    description: server

tags:
  - name: land dept
    description: Land department
  - name: 3rd party
    description: 3rd party
  - name: operations
    description: Health check operations

paths:
  /assets:
    get:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/limit"
          required: true
        - $ref: "#/components/parameters/offset"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"

      summary: Get all assets for testing

  /land/assets/list:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/limit"
          required: true
        - $ref: "#/components/parameters/offset"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"

      summary: Get all assets

  /land/assets/find:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/propertyReferenceNumber"
        - $ref: "#/components/parameters/address"
        - $ref: "#/components/parameters/limit"
          required: true
        - $ref: "#/components/parameters/offset"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Find all assets by address or property reference number

  /land/assets/get/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/GetAssetWithDetailSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get an asset by id
  /land/assets/history/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/GetAssetWithDetailSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get an asset by id with history
  /land/assets/create:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: create an asset
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/import:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: import an asset
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/update/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: update an asset with land info
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/delete/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: delete an asset
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /land/assets/lock/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: lock/freeze the access
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /land/assets/unlock/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: unlock the access
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/transaction/approve/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Approve transaction changes with asset id and record index
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/transaction/reject/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Reject transaction changes with asset id and record index
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/incumbrance/approve/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Approve incumbrance changes with asset id and record index
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/incumbrance/reject/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Reject incumbrance changes with asset id and record index
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /3rdParty/assets/find:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Find all assets by address or property reference number

  /3rdParty/assets/get/{id}:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      responses:
        "200":
          $ref: "#/components/responses/GetAssetWithDetailSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get an asset by id
  /3rdParty/assets/transaction/submit/{id}:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: submit a transaction for an asset
  /3rdParty/assets/incumbrance/submit/{id}:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: submit an incumbrance for an asset

  # Operations
  /healthz:
    get:
      tags:
        - operations
      summary: Returns 200 if the service is healthy
      responses:
        "200":
          $ref: "#/components/responses/HealthSuccess"
        "503":
          $ref: "#/components/responses/ErrorResponse"
  /readyz:
    get:
      tags:
        - operations
      summary: Returns 200 if the service is ready to accept calls
      responses:
        "200":
          $ref: "#/components/responses/HealthSuccess"
        "503":
          $ref: "#/components/responses/ErrorResponse"

components:
  responses:
    ListSuccess:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            required:
              - message
              - payload
            properties:
              count:
                type: integer
                example: 1
              message:
                type: string
                example: "ok"
              rows:
                type: array
                items:
                  $ref: "#/components/schemas/SimpleAsset"

    GetAssetWithDetailSuccess:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            required:
              - message
              - payload
            properties:
              message:
                type: string
              payload:
                $ref: "#/components/schemas/Asset"

    HealthSuccess:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: ok
            example:
              message: ok
    SuccessResponse:
      description: Success response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Success"
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    SimpleAsset:
      type: object
      description: Information about simple asset
      required:
        - id
        - propertyReferenceNumber
      properties:
        id:
          type: string
          description: id for the asset
          example: alice
        propertyReferenceNumber:
          type: string
          description: the property reference number
        propertyHeldInfos:
          type: array
          description: the property held info
          items:
            $ref: "#/components/schemas/PropertyHeldInfo"
        propertyAddress:
          type: string
          description: the property address
        propertyChineseAddress:
          type: string
          description: the property chinese address
      example:
        id: 1
        propertyReferenceNumber: "PRN-001"
        propertyHeldInfos:
          - locationNumber: "Lot 1"
            heldUnder: "PRN-001"
            leaseTerm: "1 year"
            commencementOfLeaseTerm: "2021-01-01"
            rentPerAnnum: ""
        propertyAddress: "english address"
        propertyChineseAddress: "chinese address"
    Asset:
      type: object
      description: Information about asset
      required:
        - id
        - propertyReferenceNumber
      properties:
        id:
          type: string
          description: id for the asset
          example: alice
        version:
          type: string
          description: version of the asset
        createdAt:
          type: string
          description: the create time of the asset
        updatedAt:
          type: string
          description: the update time of the asset
        createdMethod:
          type: string
          description: the create method of the asset
        propertyStatus:
          type: string
          description: the property status

        propertyReferenceNumber:
          type: string
          description: the property reference number
        propertyHeldInfos:
          type: array
          description: the property held info
          items:
            $ref: "#/components/schemas/PropertyHeldInfo"
        propertyAddress:
          type: string
          description: the property address
        propertyChineseAddress:
          type: string
          description: the property chinese address
        propertyShareOfTheLocation:
          type: string
          description: the property share of the location
        propertyRemarks:
          type: array
          description: the property remarks
          items:
            type: string
        transactionHistory:
          type: array
          description: the transaction history
          items:
            $ref: "#/components/schemas/OwnerTransactionInfo"
        deedsPendingRegistration:
          type: array
          description: the deeds pending registration
          items:
            $ref: "#/components/schemas/OwnerTransactionInfo"
        deedsPendingRegistrationRejected:
          type: array
          description: the deeds pending registration rejected
          items:
            $ref: "#/components/schemas/OwnerTransactionInfo"
        incumbranceHistory:
          type: array
          description: the incumbrance history
          items:
            $ref: "#/components/schemas/IncumbrancesInfo"
        incumbrancePendingRegistration:
          type: array
          description: the incumbrance pending registration
          items:
            $ref: "#/components/schemas/IncumbrancesInfo"
        incumbrancePendingRegistrationRejected:
          type: array
          description: the incumbrance pending registration rejected
          items:
            $ref: "#/components/schemas/IncumbrancesInfo"
    PropertyHeldInfo:
      type: object
      description: Information about  property held info
      required:
        - locationNumber
        - heldUnder
        - leaseTerm
        - commencementOfLeaseTerm
        - rentPerAnnum
      properties:
        locationNumber:
          type: string
          description: location number
        heldUnder:
          type: string
          description: held under
        leaseTerm:
          type: string
          description: lease term
        commencementOfLeaseTerm:
          type: string
          description: commencement of lease term
        rentPerAnnum:
          type: string
          description: rent per annum
      example:
        locationNumber: 1
        heldUnder: "PRN-001"
        leaseTerm: "1 year"
        commencementOfLeaseTerm: "2021-01-01"
        rentPerAnnum: ""
    OwnerInfo:
      type: object
      description: Information about an  owner
      required:
        - nameOfOwner
        - capacity
      properties:
        nameOfOwner:
          type: string
          description: name of the owner
          example: alice
        capacity:
          type: string
          description: capacity
      example:
        nameOfOwner: "alice"
        capacity: "all"
    OwnerTransactionInfo:
      type: object
      description: Information about an owner transaction
      required:
        - owners
        - memorialNumber
        - dateOfInstrument
        - dateOfRegistration
        - consideration
        - remarks
      properties:
        owners:
          type: array
          description: owner info
          items:
            $ref: "#/components/schemas/OwnerInfo"
        memorialNumber:
          type: string
          description: memorial number
          example: memorialNumber
        dateOfInstrument:
          type: string
          description: date of instrument
          example: dateOfInstrument
        dateOfRegistration:
          type: string
          description: date of registration
          example: dateOfRegistration
        consideration:
          type: string
          description: consideration
          example: consideration
        remarks:
          type: string
          description: remarks
          example: remarks field

    IncumbrancesInfo:
      type: object
      description: Information about an incumbrance
      required:
        - memorialNumber
        - dateOfInstrument
        - dateOfRegistration
        - natureOfIncumbrances
        - inFavourOf
        - consideration
        - remarks
      properties:
        owners:
          type: array
          description: owner info
          items:
            $ref: "#/components/schemas/OwnerInfo"
        memorialNumber:
          type: string
          description: memorial number
          example: memorialNumber
        dateOfInstrument:
          type: string
          description: date of instrument
          example: dateOfInstrument
        dateOfRegistration:
          type: string
          description: date of registration
          example: dateOfRegistration
        natureOfIncumbrances:
          type: string
          description: nature of incumbrances
          example: natureOfIncumbrances
        inFavourOf:
          type: string
          description: in favour of
          example: inFavourOf
        consideration:
          type: string
          description: consideration
          example: consideration
        remarks:
          type: string
          description: remarks
          example: remarks field

    Success:
      required:
        - message
        - payload
        - id
      type: object
      properties:
        message:
          description: High level success message
          type: string
        payload:
          description: Details about the data (object)
          type: object
        id:
          description: Details about the id
          type: string
      example:
        message: success message
        payload: {}
        id: "asset_id"
    Error:
      required:
        - message
        - payload
      type: object
      properties:
        message:
          description: High level error message
          type: string
        payload:
          description: Details about the error
          type: string
      example:
        message: error message
        payload: ""
  parameters:
    id:
      name: id
      schema:
        description: asset id
        type: string
        example: asset id
      in: path
      required: true
    limit:
      name: limit
      in: query
      schema:
        description: limit
        type: number
        example: 10
      required: true
    offset:
      name: offset
      in: query
      required: true
      schema:
        description: offset
        type: number
        example: 0
    propertyReferenceNumber:
      name: propertyReferenceNumber
      in: query
      schema:
        description: The Property Reference Number
        type: string
        example: "PRN-001"
    address:
      name: address
      in: query
      schema:
        description: The address of the property
        type: string
        example: "address"
  securitySchemes:
    X-Api-Key:
      type: apiKey
      in: header
      name: X-Api-Key
  headers: {}

security: []
